name: Spring blueprint generated applications
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
env:
    TEST_SCRIPTS_PATH: ${{ github.workspace }}/.github/workflows/scripts
jobs:
    spring-blueprint-image:
        name: Prepare Spring blueprint Image
        runs-on: ubuntu-latest
        concurrency:
            group: apps-dev-${{ matrix.apps }}-${{ github.head_ref || github.sha }}
            cancel-in-progress: true
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v2
            - name: Create Spring blueprint docker image
              run: |
                  docker build -t vishal423/jh:$GITHUB_SHA --build-arg UID=$(id -u) --build-arg GID=$(id -g) .
                  mkdir -p blueprint-artifacts/images
                  docker save vishal423/jh:$GITHUB_SHA > blueprint-artifacts/images/spring-blueprint-image.tar
            - name: Save Spring blueprint docker image
              uses: actions/upload-artifact@v2
              with:
                  name: docker-artifact
                  path: blueprint-artifacts/images
                  retention-days: 1
